[package]
name = "mio-singlethread"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
env_logger = "0.3"
httparse = "1.1.2"
slab = "0.2"
log = "0.3"
mio = { git = "https://github.com/carllerche/mio" }
time = "0.1"
