[package]
name = "hyper-bench"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper", rev = "0ce83dfb" }
log = "0.3"
env_logger = "0.3"
mime = "*"
